POST http://localhost:8080/api/register
Content-Type: application/json

{
    "username": "rezuan",
    "password": "1234",
    "email": "rezuan@gmail.com",
    "profile": ""
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "rezuan",
    "password": "1234"
}

###
GET http://localhost:8080/api/user/rezuan

###
PUT http://localhost:8080/api/updateuser?id=6541c015f23ab83fd225ac99
Content-Type: application/json

{
    "email": "ahmed@gmail.com",
    "profile": "base64"
}